#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# n8n bootstrap for CI / local hybrid tests.
#
# Assumes:
#   - n8n is already reachable (compose runs it with a healthcheck; use
#     `docker compose up -d --wait` to block until healthy).
#   - The instance is fresh (no owner set up yet). Re-running against an
#     already-provisioned volume will fail at owner setup; wipe
#     tests/bookshop/.n8n-data first.
#
# 1. POST /rest/owner/setup    - create owner
# 2. POST /rest/api-keys       - mint public-API JWT
# 3. Export to $GITHUB_ENV and tests/bookshop/.env.n8n
#
# Required env vars:
#   N8N_URL                    e.g. http://localhost:5678
# Optional env vars:
#   N8N_OWNER_EMAIL / N8N_OWNER_PASS / API_KEY_LABEL
# ---------------------------------------------------------------------------
set -euo pipefail

: "${N8N_URL:?N8N_URL must be set (e.g. http://localhost:5678)}"
EMAIL="${N8N_OWNER_EMAIL:-ci-owner@example.com}"
PASS="${N8N_OWNER_PASS:-Ci-Owner-Pass!23}"
LABEL="${API_KEY_LABEL:-cap-js-n8n-ci}"

JAR="$(mktemp)"; trap 'rm -f "$JAR"' EXIT
log() { printf '[n8n-bootstrap] %s\n' "$*" >&2; }

# --- 1. Owner setup --------------------------------------------------------
setup_status=$(curl -sS -o /tmp/n8n-setup.json -w '%{http_code}' -c "$JAR" \
  -H 'Content-Type: application/json' -X POST "$N8N_URL/rest/owner/setup" \
  --data "{\"email\":\"$EMAIL\",\"firstName\":\"CI\",\"lastName\":\"Owner\",\"password\":\"$PASS\"}")

if [ "$setup_status" != "200" ] && [ "$setup_status" != "201" ]; then
  log "Owner setup failed (HTTP $setup_status):"
  cat /tmp/n8n-setup.json >&2
  log "If the instance is already provisioned, run 'docker compose down -v' and retry."
  exit 1
fi
log "Owner account created ($EMAIL)"

# --- 2. Mint an API key ----------------------------------------------------
SCOPES='["workflow:create","workflow:read","workflow:update","workflow:delete","workflow:list","workflow:move","workflow:activate","workflow:deactivate","workflow:export","workflow:import","execution:read","execution:list","execution:delete","execution:retry","execution:stop","credential:create","credential:read","credential:update","credential:delete","credential:list","credential:move","tag:create","tag:read","tag:update","tag:delete","tag:list","variable:create","variable:update","variable:delete","variable:list","project:create","project:update","project:delete","project:list","user:create","user:read","user:list","user:delete","user:changeRole"]'

key_status=$(curl -sS -o /tmp/n8n-key.json -w '%{http_code}' -b "$JAR" \
  -H 'Content-Type: application/json' -X POST "$N8N_URL/rest/api-keys" \
  --data "{\"label\":\"$LABEL\",\"expiresAt\":null,\"scopes\":$SCOPES}")

if [ "$key_status" != "200" ] && [ "$key_status" != "201" ]; then
  log "API key creation failed (HTTP $key_status):"; cat /tmp/n8n-key.json >&2; exit 1
fi

RAW_KEY=$(node -e '
  const b = JSON.parse(require("fs").readFileSync("/tmp/n8n-key.json","utf8"));
  process.stdout.write((b.data || b).rawApiKey || "");
')

if [ -z "$RAW_KEY" ]; then
  log "rawApiKey missing from response:"; cat /tmp/n8n-key.json >&2; exit 1
fi

log "API key '$LABEL' minted"

# --- 3. Export -------------------------------------------------------------
printf '%s\n' "$RAW_KEY"

if [ -n "${GITHUB_ENV:-}" ]; then
  { echo "N8N_API_KEY=$RAW_KEY"; echo "N8N_URL=$N8N_URL"; } >> "$GITHUB_ENV"
  log "Exported N8N_API_KEY to \$GITHUB_ENV"
fi

target_env="$(cd "$(dirname "$0")/.." && pwd)/tests/bookshop/.env.n8n"
{ echo "# Auto-generated by scripts/n8n-bootstrap.sh - do not commit"
  echo "N8N_API_KEY=$RAW_KEY"; } > "$target_env"
log "Wrote $target_env"
